### ISSUE TITLE
Practical workflow

### ISSUE THREAD

**Issue by albertgarciandres** [galantelab/fredy#1]
# Practical workflow

I have been doing the practical workflow to get to know with FREDDIE for later usage. The installation as well as the download phase has been simple. However, I have had some troubles whenever executing the FREDDIE steps.

## "Chimeric" step:

Whenever executing the "chimeric" step it gives the following error:
```
Error: Sorted input specified, but the file /home/freddie/db/RCP_9606.bed4 has the following output of order record
chr10         10174153         10174785         ELOCP3

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
```

I have been searching for the error and found that the problem is caused due to a [bedtools] malfunction on the `.bed4` file. 
To solve the issue I executed the following command:
```
sort -k 1,1 -k2,2n RCP_9606.bed4 > RCP_9606.sort.bed4
```

Once I have modified the corresponding file I could execute back again the "chimeric" step command without any further troubles as follows:
```
time docker run --rm -u $(id -u):$(id -g) -w $(pwd) \
-v $PWD:/home/freddie freddie chimeric \
-o /home/freddie/K562 \
-a /home/freddie/db/gencode.v36.annotation.gtf \
-g /home/freddie/db/hg38.fa \
-e /home/freddie/db/RCP_9606.sort.bed4
```
As can be seen, this time instead of having the `RCP_9606.bed4` file as the output event file (-e parameter), I am using the previously created file `RCP_9606.sort.bed4`.

## "Coding" step:

Another easy-to-solve issue is right after the "chimeric" step. This time what happens is that there is no section providing the code to run the "coding" step. If we proceed, once the "chimeric" step has been done, right now it tells us to execute the "pfam" step. Whenever doing so, the terminal will inform us that to do this step we need to previously do the "coding" step. This is why, with the help of the [coding] section I could solve the issue.

The code goes as follows:
```
time docker run --rm -u $(id -u):$(id -g) -w $(pwd) \
-v $PWD:/home/freddie freddie coding \
-o /home/freddie/K562 \
-m /home/freddie/db/human38_model.hdf5 \
-d /home/freddie/db/hg38.pep.fa
```

With the following modifications, we can continue with the remaining steps of the practical workflow to finally obtain the desired `results.tsv` file without any more troubles. 

Hope it was helpful,

Albert

[bedtools]: <https://bedtools.readthedocs.io/en/latest/content/overview.html>
[coding]: <https://github.com/galantelab/freddie/tree/main?tab=readme-ov-file#coding>

**Comment by rmercuri** [comment]
Hi @albertgarciandres,

Thank you very much for your review.

Regarding the BED file, it is indeed strange as it should have already been sorted. However, since it apparently isn't, we will incorporate the sorting command in the practical workflow. As for the coding command, I have uploaded the practical workflow based on the supplementary material of the article, but due to my oversight (haha), I forgot to add the command.

Thank you again, and if you need any help with the pipeline, feel free to contact me via email. Additionally, if possible, please provide a review of your experience using the tool with your data (Attended your expectations? haha).

PS.: I will upload a new version (asap), we have a bug in a counting of number os samples which the transcript is expressed (5th column in the results.tsv).

**Comment by rmercuri** [comment]
I will close this issue. Thanks once again!
