### ISSUE TITLE
permission to download database

### ISSUE THREAD

**Issue by mingwhy** [galantelab/fredy#3]
Hi Thiago L. A. Miller,

Thank you for making this amazing tool! I'm interested in applying this tool to our in-house tumor RNA-seq dataset.

I've pulled a docker image of fredy, and when I was trying to set up the database, the download links for files like 'hg38.pep.fa' and 'model.hdf5' are access forbidden.

I'm wondering is there any other way to get the requried files?

Thank you!
Best regards,
Ming

**Comment by thiago-miller** [comment]
Hi Mr. Ming,

First of all, thank you for using Fredy. I hope the tool meets your expectations.

I have looked into the issue you reported, and indeed, those links are currently inaccessible due to permission restrictions.

All the files are hosted on our AWS buckets, and we will resolve this issue as soon as possible.

I will inform you once everything is back up and running.

Thank you for bringing this to our attention.

Best regards,
Thiago L. A. Miller

**Comment by rmercuri** [comment]
Hello!  

We had an issue with the link assignment, but everything is working again now. Thank you for letting us know!

Best,
Rafael Mercuri
